//! Host-agnostic application services for Pantograph workflow use-cases.
//!
//! This crate owns service-level request/response contracts and orchestration
//! interfaces. Transport adapters (Tauri/UniFFI/Rustler) should delegate into
//! this crate rather than duplicate business logic.

// Force linker to include workflow-nodes inventory::submit!() statics so the
// graph registry can discover built-in descriptors in headless consumers too.
extern crate workflow_nodes;

pub mod capabilities;
pub mod graph;
mod scheduler;
pub mod technical_fit;
pub mod trace;
pub mod workflow;

pub use graph::{
    convert_graph_from_node_engine, convert_graph_to_node_engine,
    graph_memory_impact_from_node_engine_graph_change, validate_workflow_connection,
    validate_workflow_graph_contract, validate_workflow_graph_contract_diagnostics,
    workflow_executable_topology, workflow_executable_topology_with_node_versions,
    workflow_execution_fingerprint, workflow_execution_fingerprint_for_topology,
    workflow_graph_run_settings, workflow_graph_run_settings_json,
    workflow_presentation_fingerprint, workflow_presentation_fingerprint_for_metadata,
    workflow_presentation_metadata, workflow_presentation_metadata_json, ConnectionAnchor,
    ConnectionCandidatesResponse, ConnectionCommitResponse, ConnectionRejection,
    ConnectionRejectionReason, ConnectionTargetAnchorCandidate, ConnectionTargetNodeCandidate,
    EdgeInsertionBridge, EdgeInsertionPreviewResponse, ExecutionMode, FileSystemWorkflowGraphStore,
    GraphEdge, GraphNode, InsertNodeConnectionResponse, InsertNodeOnEdgeResponse,
    InsertNodePositionHint, InsertableNodeTypeCandidate, IoBindingOrigin, NodeCategory,
    NodeDefinition, NodeGroup, NodeRegistry, PortDataType, PortDefinition, PortMapping, Position,
    UndoRedoState, Viewport, WorkflowExecutableTopology, WorkflowExecutableTopologyEdge,
    WorkflowExecutableTopologyNode, WorkflowFile, WorkflowGraph, WorkflowGraphAddEdgeRequest,
    WorkflowGraphAddNodeRequest, WorkflowGraphConnectRequest, WorkflowGraphCreateGroupRequest,
    WorkflowGraphCurrentValidationRefreshRequest, WorkflowGraphCurrentValidationRefreshResponse,
    WorkflowGraphCurrentValidationSummaryRequest, WorkflowGraphCurrentValidationSummaryResponse,
    WorkflowGraphCurrentValidationSummaryState, WorkflowGraphDeleteRequest,
    WorkflowGraphDeleteResponse, WorkflowGraphDeleteSelectionRequest, WorkflowGraphDiagnostic,
    WorkflowGraphDiagnosticCode, WorkflowGraphDiagnosticScope, WorkflowGraphDiagnosticSeverity,
    WorkflowGraphEditSessionCloseRequest, WorkflowGraphEditSessionCloseResponse,
    WorkflowGraphEditSessionCreateRequest, WorkflowGraphEditSessionCreateResponse,
    WorkflowGraphEditSessionGraphRequest, WorkflowGraphEditSessionGraphResponse,
    WorkflowGraphGetConnectionCandidatesRequest, WorkflowGraphInsertNodeAndConnectRequest,
    WorkflowGraphInsertNodeOnEdgeRequest, WorkflowGraphInspectionProjection,
    WorkflowGraphInspectionRequest, WorkflowGraphInspectionRunContext,
    WorkflowGraphInspectionSelectedNode, WorkflowGraphListResponse, WorkflowGraphLoadRequest,
    WorkflowGraphMetadata, WorkflowGraphPreviewNodeInsertOnEdgeRequest,
    WorkflowGraphRemoveEdgeRequest, WorkflowGraphRemoveEdgesRequest,
    WorkflowGraphRemoveNodeRequest, WorkflowGraphRunSettings, WorkflowGraphRunSettingsNode,
    WorkflowGraphSaveRequest, WorkflowGraphSaveResponse, WorkflowGraphStore,
    WorkflowGraphUndoRedoStateRequest, WorkflowGraphUndoRedoStateResponse,
    WorkflowGraphUngroupRequest, WorkflowGraphUpdateGroupPortsRequest,
    WorkflowGraphUpdateNodeDataRequest, WorkflowGraphUpdateNodePositionRequest,
    WorkflowGraphValidationLifecycleEvent, WorkflowGraphValidationLifecycleEventKind,
    WorkflowGraphValidationLifecycleEventSink, WorkflowGraphValidationLifecycleEventSnapshot,
    WorkflowGraphValidationSubmitGate, WorkflowGraphValidationSubmitGateReason,
    WorkflowPresentationEdge, WorkflowPresentationMetadata, WorkflowPresentationNode,
};
pub use pantograph_runtime_attribution::{ClientSessionId, WorkflowId, WorkflowRunId};
pub use scheduler::{
    select_runtime_unload_candidate_by_affinity, WorkflowSchedulerRuntimeCapacityPressure,
    WorkflowSchedulerRuntimeRegistryDiagnostics, WorkflowSchedulerRuntimeWarmupDecision,
    WorkflowSchedulerRuntimeWarmupReason, WorkflowSchedulerSnapshotDiagnostics,
};
pub use technical_fit::{
    build_workflow_technical_fit_request, WorkflowTechnicalFitCandidateSetSummary,
    WorkflowTechnicalFitCompatibilityIssue, WorkflowTechnicalFitCompatibilityReport,
    WorkflowTechnicalFitDecision, WorkflowTechnicalFitDecisionCode,
    WorkflowTechnicalFitDependencyReadinessFact,
    WorkflowTechnicalFitDependencyReadinessResolverOwner,
    WorkflowTechnicalFitDependencyReadinessState,
    WorkflowTechnicalFitDependencyReadinessSubjectKind, WorkflowTechnicalFitDeviceClass,
    WorkflowTechnicalFitDeviceDiagnostic, WorkflowTechnicalFitDeviceDiagnosticCode,
    WorkflowTechnicalFitDeviceDiagnosticSeverity, WorkflowTechnicalFitDevicePolicy,
    WorkflowTechnicalFitHistoryThresholdState, WorkflowTechnicalFitObservedThroughputHint,
    WorkflowTechnicalFitOverride, WorkflowTechnicalFitPolicyPhase,
    WorkflowTechnicalFitQueuePressure, WorkflowTechnicalFitReason, WorkflowTechnicalFitReasonCode,
    WorkflowTechnicalFitRequest, WorkflowTechnicalFitResourceEstimate,
    WorkflowTechnicalFitResourceEstimateDiagnostic,
    WorkflowTechnicalFitResourceEstimateDiagnosticCode,
    WorkflowTechnicalFitResourceEstimateDiagnosticSeverity,
    WorkflowTechnicalFitResourceEstimateKind, WorkflowTechnicalFitResourceEstimateState,
    WorkflowTechnicalFitSelectionMode, WorkflowTechnicalFitSelectionPolicyTrace,
    WorkflowTechnicalFitUnavailableResourceEstimateState,
};
pub use trace::{
    WorkflowTraceEvent, WorkflowTraceGraphContext, WorkflowTraceGraphTimingExpectations,
    WorkflowTraceNodeRecord, WorkflowTraceNodeStatus, WorkflowTraceNodeTimingExpectation,
    WorkflowTraceQueueMetrics, WorkflowTraceRecordResult, WorkflowTraceRuntimeMetrics,
    WorkflowTraceRuntimeSelection, WorkflowTraceSnapshotRequest, WorkflowTraceSnapshotResponse,
    WorkflowTraceStatus, WorkflowTraceStore, WorkflowTraceSummary,
};
pub use workflow::{
    evaluate_runtime_preflight, format_runtime_not_ready_message, ArtifactAccessMode,
    ArtifactAttribution, ArtifactBodyRead, ArtifactBodyTransport,
    ArtifactConsumeAcknowledgementRequest, ArtifactConsumeAcknowledgementResponse,
    ArtifactConversionDependency, ArtifactConversionStatus, ArtifactDescriptor,
    ArtifactDescriptorQueryRequest, ArtifactDescriptorQueryResponse, ArtifactFormatCapabilities,
    ArtifactFormatDependencyVersion, ArtifactFormatDependencyVersions, ArtifactFormatMetadata,
    ArtifactFormatSettings, ArtifactFormatSettingsQueryRequest,
    ArtifactFormatSettingsQueryResponse, ArtifactFormatSettingsUpdateRequest,
    ArtifactFormatSettingsUpdateResponse, ArtifactLifecycleState, ArtifactPayloadKind,
    ArtifactPolicy, ArtifactReadRequest, ArtifactReadResponse, ArtifactStore, ArtifactStoreError,
    ArtifactStoreStats, ArtifactStreamBodyRead, ArtifactStreamChunkRecord,
    ArtifactStreamChunkWriteRequest, ArtifactStreamFinalizeRequest, ArtifactStreamOpenRequest,
    ArtifactStreamReadRequest, ArtifactStreamReadResponse, ArtifactWriteRequest,
    AudioArtifactFormatSettings, BucketCreateRequest, BucketDeleteRequest, BucketRecord,
    BucketSelection, ClientRegistrationRequest, ClientRegistrationResponse,
    ClientSessionOpenRequest, ClientSessionOpenResponse, ClientSessionRecord,
    ClientSessionResumeRequest, CredentialProofRequest, CredentialSecret,
    ImageArtifactFormatSettings, InMemoryWorkflowExecutableValidationSnapshotStore,
    LibraryAssetCacheStatus, LibraryAssetOperation, ManagedRedistributableCategory,
    ManagedRedistributableReadinessState, ManagedRedistributableStatus,
    ManagedRedistributableStatusQueryResponse, MediaFormatOption, ThreeDArtifactFormatSettings,
    ValidatedWorkflowExecutableValidationSnapshotRecord, VideoArtifactFormatSettings,
    WorkflowAdminQueueCancelRequest, WorkflowAdminQueueCancelResponse,
    WorkflowAdminQueuePushFrontRequest, WorkflowAdminQueuePushFrontResponse,
    WorkflowAdminQueueReprioritizeRequest, WorkflowAdminQueueReprioritizeResponse,
    WorkflowBackendCapabilityFacts, WorkflowBackendComponentCapability,
    WorkflowBackendFeatureCapabilityFacts, WorkflowBackendFeatureSupport, WorkflowBackendHintLabel,
    WorkflowBackendModelSourceCapabilityFacts, WorkflowBackendRequestCancellationSemantics,
    WorkflowBackendRequestCleanupSemantics, WorkflowBackendRequestLifecycleFacts,
    WorkflowBackendRequestLifecyclePhaseFacts, WorkflowBackendTaskCapability,
    WorkflowCapabilitiesRequest, WorkflowCapabilitiesResponse, WorkflowCapabilityModel,
    WorkflowDeviceResolutionDiagnostic, WorkflowDeviceResolutionDiagnosticCode,
    WorkflowDeviceResolutionDiagnosticSeverity, WorkflowDiagnosticEventRecordResponse,
    WorkflowDiagnosticsProjectionAdvance, WorkflowDiagnosticsProjectionFailure,
    WorkflowDiagnosticsProjectionInvalidation, WorkflowDiagnosticsProjectionKind,
    WorkflowDiagnosticsProjectionRefreshReason, WorkflowDiagnosticsProjectionRefreshRequest,
    WorkflowDiagnosticsProjectionRefreshResponse, WorkflowDiagnosticsProjectionRefreshSink,
    WorkflowDiagnosticsUsageQueryRequest, WorkflowDiagnosticsUsageQueryResponse,
    WorkflowDiagnosticsUsageSummary, WorkflowErrorCode, WorkflowErrorDetails,
    WorkflowErrorEnvelope, WorkflowExecutableValidationSnapshotDiagnostic,
    WorkflowExecutableValidationSnapshotDiagnosticCode,
    WorkflowExecutableValidationSnapshotDiagnosticSeverity,
    WorkflowExecutableValidationSnapshotError, WorkflowExecutableValidationSnapshotId,
    WorkflowExecutableValidationSnapshotLookupRequest, WorkflowExecutableValidationSnapshotNode,
    WorkflowExecutableValidationSnapshotPublishRequest, WorkflowExecutableValidationSnapshotRecord,
    WorkflowExecutionPlan, WorkflowExecutionPlanDiagnostic, WorkflowExecutionPlanDiagnosticCode,
    WorkflowExecutionPlanDiagnosticSeverity, WorkflowExecutionPlanError,
    WorkflowExecutionPlanNodeDecision, WorkflowExecutionSessionAttributedCreateRequest,
    WorkflowExecutionSessionAttributionContext, WorkflowExecutionSessionAttributionRequest,
    WorkflowExecutionSessionCloseRequest, WorkflowExecutionSessionCloseResponse,
    WorkflowExecutionSessionCreateRequest, WorkflowExecutionSessionCreateResponse,
    WorkflowExecutionSessionInspectionRequest, WorkflowExecutionSessionInspectionResponse,
    WorkflowExecutionSessionKeepAliveRequest, WorkflowExecutionSessionKeepAliveResponse,
    WorkflowExecutionSessionQueueCancelRequest, WorkflowExecutionSessionQueueCancelResponse,
    WorkflowExecutionSessionQueueItem, WorkflowExecutionSessionQueueItemStatus,
    WorkflowExecutionSessionQueueListRequest, WorkflowExecutionSessionQueueListResponse,
    WorkflowExecutionSessionQueuePushFrontRequest, WorkflowExecutionSessionQueuePushFrontResponse,
    WorkflowExecutionSessionQueueReprioritizeRequest,
    WorkflowExecutionSessionQueueReprioritizeResponse, WorkflowExecutionSessionRetentionHint,
    WorkflowExecutionSessionRunRequest, WorkflowExecutionSessionRuntimeSelectionTarget,
    WorkflowExecutionSessionRuntimeUnloadCandidate, WorkflowExecutionSessionStaleCleanupRequest,
    WorkflowExecutionSessionStaleCleanupResponse, WorkflowExecutionSessionStaleCleanupWorker,
    WorkflowExecutionSessionStaleCleanupWorkerConfig, WorkflowExecutionSessionState,
    WorkflowExecutionSessionStatusRequest, WorkflowExecutionSessionStatusResponse,
    WorkflowExecutionSessionSummary, WorkflowExecutionSessionUnloadReason,
    WorkflowGraphErrorDetails, WorkflowGraphSessionExecutableValidationSnapshotPublishRequest,
    WorkflowHost, WorkflowHostCapabilities, WorkflowHostModelDescriptor, WorkflowIdentity,
    WorkflowIdentityError, WorkflowInferenceDeviceClass, WorkflowInferenceExecutionInputKind,
    WorkflowInferenceExecutionResultKind, WorkflowInferenceLifecyclePhase,
    WorkflowInferenceModality, WorkflowInferenceTaskId, WorkflowInputTarget,
    WorkflowIoArtifactQueryRequest, WorkflowIoArtifactQueryResponse, WorkflowIoNode,
    WorkflowIoPort, WorkflowIoRequest, WorkflowIoResponse, WorkflowLibraryAssetAccessRecordRequest,
    WorkflowLibraryAssetAccessRecordResponse, WorkflowLibraryUsageQueryRequest,
    WorkflowLibraryUsageQueryResponse, WorkflowLocalCpuMetrics, WorkflowLocalDiskMetrics,
    WorkflowLocalGpuMetrics, WorkflowLocalMemoryMetrics, WorkflowLocalNetworkInterfaceMetrics,
    WorkflowLocalNetworkNodeStatus, WorkflowLocalNetworkStatusQueryRequest,
    WorkflowLocalNetworkStatusQueryResponse, WorkflowLocalSchedulerLoad,
    WorkflowLocalSystemMetrics, WorkflowModelArtifactKind, WorkflowNetworkTransportState,
    WorkflowNodeStatusQueryRequest, WorkflowNodeStatusQueryResponse, WorkflowOutputTarget,
    WorkflowPeerNetworkNodeStatus, WorkflowPortBinding, WorkflowPreflightRequest,
    WorkflowPreflightResponse, WorkflowPresentationRevisionRecord,
    WorkflowPresentationRevisionResolveRequest, WorkflowProjectionRebuildRequest,
    WorkflowProjectionRebuildResponse, WorkflowRetentionCleanupRequest,
    WorkflowRetentionCleanupResponse, WorkflowRetentionPolicyQueryRequest,
    WorkflowRetentionPolicyQueryResponse, WorkflowRetentionPolicyUpdateRequest,
    WorkflowRetentionPolicyUpdateResponse, WorkflowRunAttribution, WorkflowRunAttributionContext,
    WorkflowRunAttributionResolveRequest, WorkflowRunDetailQueryRequest,
    WorkflowRunDetailQueryResponse, WorkflowRunGraphProjection, WorkflowRunGraphQueryRequest,
    WorkflowRunGraphQueryResponse, WorkflowRunHandle, WorkflowRunInspectionQueryRequest,
    WorkflowRunInspectionQueryResponse, WorkflowRunListQueryRequest, WorkflowRunListQueryResponse,
    WorkflowRunOptions, WorkflowRunRecord, WorkflowRunRequest, WorkflowRunResponse,
    WorkflowRunSnapshotRecord, WorkflowRunSnapshotRequest, WorkflowRunVersionProjection,
    WorkflowRuntimeCapability, WorkflowRuntimeDiagnosticPhaseHint, WorkflowRuntimeInstallState,
    WorkflowRuntimeIssue, WorkflowRuntimeReadinessState, WorkflowRuntimeRequirements,
    WorkflowRuntimeSourceKind, WorkflowRuntimeVariantCapability, WorkflowSchedulerAdmissionOutcome,
    WorkflowSchedulerDecisionReason, WorkflowSchedulerDiagnosticsProvider,
    WorkflowSchedulerErrorDetails, WorkflowSchedulerErrorReason,
    WorkflowSchedulerEstimateQueryRequest, WorkflowSchedulerEstimateQueryResponse,
    WorkflowSchedulerEstimateRecord, WorkflowSchedulerNonRuntimeTaskTemplate,
    WorkflowSchedulerRuntimeDiagnosticsRequest, WorkflowSchedulerSnapshotRequest,
    WorkflowSchedulerSnapshotResponse, WorkflowSchedulerSourceInputTemplate, WorkflowSchedulerTask,
    WorkflowSchedulerTaskExecutionClass, WorkflowSchedulerTaskGraph,
    WorkflowSchedulerTaskInputBinding, WorkflowSchedulerTaskProjectionDiagnostic,
    WorkflowSchedulerTaskProjectionDiagnosticCode,
    WorkflowSchedulerTaskProjectionDiagnosticSeverity, WorkflowSchedulerTimelineQueryRequest,
    WorkflowSchedulerTimelineQueryResponse, WorkflowService, WorkflowServiceError,
    WorkflowSessionRuntimeLoadProof, WorkflowSupportTier, WorkflowTaskModalitySignature,
    WorkflowTaskRequestContract, WorkflowTaskStreamingSupport, WorkflowVersionRecord,
    WorkflowVersionResolveRequest,
    WORKFLOW_EXECUTABLE_VALIDATION_SNAPSHOT_MAX_DIAGNOSTICS_PER_NODE,
    WORKFLOW_EXECUTABLE_VALIDATION_SNAPSHOT_MAX_ESTIMATE_HINTS_PER_NODE,
    WORKFLOW_EXECUTABLE_VALIDATION_SNAPSHOT_MAX_NODES,
    WORKFLOW_EXECUTABLE_VALIDATION_SNAPSHOT_MAX_TRAIT_SETTINGS_PER_NODE,
    WORKFLOW_EXECUTABLE_VALIDATION_SNAPSHOT_SCHEMA_VERSION,
    WORKFLOW_EXECUTION_PLAN_MAX_DIAGNOSTICS, WORKFLOW_EXECUTION_PLAN_MAX_NODE_DECISIONS,
    WORKFLOW_EXECUTION_PLAN_MAX_POLICY_TRACE_IDS, WORKFLOW_EXECUTION_PLAN_SCHEMA_VERSION,
    WORKFLOW_SCHEDULER_TASK_GRAPH_SCHEMA_VERSION,
};
pub use workflow::{
    IoArtifactProjectionRecord, IoArtifactRetentionState, IoArtifactRetentionSummaryRecord,
    LibraryUsageProjectionRecord, ProjectionStateRecord, ResolvedNodeIoDirection,
    ResolvedNodeIoProvenanceKind, ResolvedNodeIoRecord, ResolvedNodeIoResolution,
    RunDetailProjectionRecord, RunListFacetRecord, RunListProjectionRecord,
    RunListProjectionStatus, SchedulerModelCacheState, SchedulerTimelineProjectionRecord,
    SqliteDiagnosticsLedger, WorkflowTimingExpectation, WorkflowTimingExpectationComparison,
};
