//! Masked Text Input Task
//!
//! Input node for text with masked and anchored regions. Masked regions
//! are regenerated by dLLM models while anchored regions are preserved
//! as context.
//!
//! # Inputs (from context)
//! - `{task_id}.input.text` (optional) - Initial text or upstream text
//!
//! # Outputs (to context)
//! - `{task_id}.output.masked_prompt` - Structured JSON with segments

use async_trait::async_trait;
use graph_flow::{Context, NextAction, Task, TaskResult};
use node_engine::{
    ContextKeys, ExecutionMode, NodeCategory, PortDataType, PortMetadata, TaskDescriptor,
    TaskMetadata,
};
use serde::{Deserialize, Serialize};

/// A segment of text that is either masked (regenerated) or anchored (preserved).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TextSegment {
    /// The text content of this segment.
    pub text: String,
    /// Whether this segment is masked (true) or anchored (false).
    pub masked: bool,
}

/// Masked Text Input Task
///
/// Provides text with mixed anchor/mask regions for selective dLLM regeneration.
/// The UI component allows users to select text regions and mark them as
/// anchored (preserved) or masked (regenerated).
///
/// # Inputs (from context)
/// - `{task_id}.input.text` (optional) - Initial text or upstream text
///
/// # Outputs (to context)
/// - `{task_id}.output.masked_prompt` - Structured JSON with segments
#[derive(Clone)]
pub struct MaskedTextInputTask {
    /// Unique identifier for this task instance
    task_id: String,
}

impl MaskedTextInputTask {
    /// Port ID for text input
    pub const PORT_TEXT: &'static str = "text";
    /// Port ID for masked prompt output
    pub const PORT_MASKED_PROMPT: &'static str = "masked_prompt";

    /// Create a new masked text input task
    pub fn new(task_id: impl Into<String>) -> Self {
        Self {
            task_id: task_id.into(),
        }
    }

    /// Get the task ID
    pub fn task_id(&self) -> &str {
        &self.task_id
    }
}

impl TaskDescriptor for MaskedTextInputTask {
    fn descriptor() -> TaskMetadata {
        TaskMetadata {
            node_type: "masked-text-input".to_string(),
            category: NodeCategory::Input,
            label: "Masked Text Input".to_string(),
            description: "Text input with masked and anchored regions for selective dLLM regeneration".to_string(),
            inputs: vec![PortMetadata::optional(
                Self::PORT_TEXT,
                "Text",
                PortDataType::String,
            )],
            outputs: vec![PortMetadata::required(
                Self::PORT_MASKED_PROMPT,
                "Masked Prompt",
                PortDataType::Prompt,
            )],
            execution_mode: ExecutionMode::Reactive,
        }
    }
}

inventory::submit!(node_engine::DescriptorFn(MaskedTextInputTask::descriptor));

#[async_trait]
impl Task for MaskedTextInputTask {
    fn id(&self) -> &str {
        &self.task_id
    }

    async fn run(&self, context: Context) -> graph_flow::Result<TaskResult> {
        // Try to get segment data from the meta key (set by the UI component)
        let data_key = ContextKeys::meta(&self.task_id, "data");
        let segments_json: Option<String> = context.get(&data_key).await;

        let masked_prompt = if let Some(ref json_str) = segments_json {
            // Parse segments from the UI-provided data
            if let Ok(segments) = serde_json::from_str::<Vec<TextSegment>>(json_str) {
                serde_json::json!({
                    "type": "masked_prompt",
                    "segments": segments,
                })
            } else {
                // If parsing fails, treat the raw string as a single masked segment
                serde_json::json!({
                    "type": "masked_prompt",
                    "segments": [{ "text": json_str, "masked": true }],
                })
            }
        } else {
            // Fall back to the text input port and treat entire text as masked
            let input_key = ContextKeys::input(&self.task_id, Self::PORT_TEXT);
            let text: String = context.get(&input_key).await.unwrap_or_default();

            serde_json::json!({
                "type": "masked_prompt",
                "segments": [{ "text": text, "masked": true }],
            })
        };

        // Store output in context
        let output_key = ContextKeys::output(&self.task_id, Self::PORT_MASKED_PROMPT);
        let output_str = serde_json::to_string(&masked_prompt).unwrap_or_default();
        context.set(&output_key, output_str.clone()).await;

        let segment_count = masked_prompt
            .get("segments")
            .and_then(|s| s.as_array())
            .map(|a| a.len())
            .unwrap_or(0);

        let summary = format!("Masked prompt with {} segment(s)", segment_count);

        log::debug!(
            "MaskedTextInputTask {}: produced {}",
            self.task_id,
            summary
        );

        Ok(TaskResult::new(Some(summary), NextAction::Continue))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_task_id() {
        let task = MaskedTextInputTask::new("my_input");
        assert_eq!(task.id(), "my_input");
    }

    #[test]
    fn test_descriptor_node_type() {
        let meta = MaskedTextInputTask::descriptor();
        assert_eq!(meta.node_type, "masked-text-input");
    }

    #[test]
    fn test_descriptor_category() {
        let meta = MaskedTextInputTask::descriptor();
        assert_eq!(meta.category, NodeCategory::Input);
    }

    #[test]
    fn test_descriptor_ports() {
        let meta = MaskedTextInputTask::descriptor();
        assert_eq!(meta.inputs.len(), 1);
        assert!(!meta.inputs[0].required, "text input should be optional");
        assert_eq!(meta.outputs.len(), 1);
        assert!(meta.outputs[0].required, "masked_prompt output should be required");
    }

    #[test]
    fn test_text_segment_serialize() {
        let segment = TextSegment {
            text: "Hello world".to_string(),
            masked: true,
        };
        let json = serde_json::to_string(&segment).unwrap();
        assert!(json.contains("\"text\":\"Hello world\""));
        assert!(json.contains("\"masked\":true"));

        let deserialized: TextSegment = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.text, "Hello world");
        assert!(deserialized.masked);
    }

    #[tokio::test]
    async fn test_run_with_text_input_treats_as_masked() {
        let task = MaskedTextInputTask::new("test_masked");
        let context = Context::new();

        // Set input text on the text port
        let input_key = ContextKeys::input("test_masked", "text");
        context
            .set(&input_key, "The quick brown fox".to_string())
            .await;

        // Run task
        let result = task.run(context.clone()).await.unwrap();
        assert!(matches!(result.next_action, NextAction::Continue));
        assert_eq!(
            result.response.as_deref(),
            Some("Masked prompt with 1 segment(s)")
        );

        // Verify output was stored
        let output_key = ContextKeys::output("test_masked", "masked_prompt");
        let output: Option<String> = context.get(&output_key).await;
        assert!(output.is_some());

        let parsed: serde_json::Value = serde_json::from_str(&output.unwrap()).unwrap();
        assert_eq!(parsed["type"], "masked_prompt");
        let segments = parsed["segments"].as_array().unwrap();
        assert_eq!(segments.len(), 1);
        assert_eq!(segments[0]["text"], "The quick brown fox");
        assert_eq!(segments[0]["masked"], true);
    }

    #[tokio::test]
    async fn test_run_with_segments_from_meta() {
        let task = MaskedTextInputTask::new("test_masked");
        let context = Context::new();

        // Set segments via the meta key (as the UI would)
        let data_key = ContextKeys::meta("test_masked", "data");
        let segments = serde_json::json!([
            { "text": "Hello ", "masked": false },
            { "text": "world", "masked": true }
        ]);
        context
            .set(&data_key, serde_json::to_string(&segments).unwrap())
            .await;

        // Run task
        let result = task.run(context.clone()).await.unwrap();
        assert!(matches!(result.next_action, NextAction::Continue));
        assert_eq!(
            result.response.as_deref(),
            Some("Masked prompt with 2 segment(s)")
        );

        // Verify output
        let output_key = ContextKeys::output("test_masked", "masked_prompt");
        let output: Option<String> = context.get(&output_key).await;
        let parsed: serde_json::Value = serde_json::from_str(&output.unwrap()).unwrap();
        assert_eq!(parsed["type"], "masked_prompt");
        let segs = parsed["segments"].as_array().unwrap();
        assert_eq!(segs.len(), 2);
        assert_eq!(segs[0]["text"], "Hello ");
        assert_eq!(segs[0]["masked"], false);
        assert_eq!(segs[1]["text"], "world");
        assert_eq!(segs[1]["masked"], true);
    }

    #[tokio::test]
    async fn test_run_empty_input() {
        let task = MaskedTextInputTask::new("test_masked");
        let context = Context::new();

        // Run without setting any input — should default to empty text, single masked segment
        let result = task.run(context.clone()).await.unwrap();
        assert!(matches!(result.next_action, NextAction::Continue));

        let output_key = ContextKeys::output("test_masked", "masked_prompt");
        let output: Option<String> = context.get(&output_key).await;
        let parsed: serde_json::Value = serde_json::from_str(&output.unwrap()).unwrap();
        let segments = parsed["segments"].as_array().unwrap();
        assert_eq!(segments.len(), 1);
        assert_eq!(segments[0]["text"], "");
        assert_eq!(segments[0]["masked"], true);
    }
}
